export enum ServiceTypes {
  USER_DASHBOARD = "USER_DASHBOARD",
  ADMIN_DASHBOARD = "ADMIN_DASHBOARD",
  ALL_PRODUCTS = "ALL_PRODUCTS",
  REGISTER_PRODUCT = "REGISTER_PRODUCT",
  DEVELOPERS = "DEVELOPERS",
  DEMO_WEBSITE = "DEMO_WEBSITE",
}
