/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides, Signer, utils } from "ethers";
import type { IncentivePoolView, IncentivePoolViewInterface } from "../IncentivePoolView";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "factory_",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061001961001e565b6100dd565b600054610100900460ff161561008a5760405162461bcd60e51b815260206004820152602760248201527f496e697469616c697a61626c653a20636f6e747261637420697320696e697469604482015266616c697a696e6760c81b606482015260840160405180910390fd5b60005460ff908116146100db576000805460ff191660ff9081179091556040519081527f7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb38474024989060200160405180910390a15b565b61021b806100ec6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063c45a01551461003b578063c4d66de814610070575b600080fd5b600054610054906201000090046001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b61008361007e3660046101b5565b610085565b005b600054610100900460ff16158080156100a55750600054600160ff909116105b806100bf5750303b1580156100bf575060005460ff166001145b6101265760405162461bcd60e51b815260206004820152602e60248201527f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160448201526d191e481a5b9a5d1a585b1a5e995960921b606482015260840160405180910390fd5b6000805460ff191660011790558015610149576000805461ff0019166101001790555b6000805462010000600160b01b031916620100006001600160a01b0385160217905580156101b1576000805461ff0019169055604051600181527f7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb38474024989060200160405180910390a15b5050565b6000602082840312156101c757600080fd5b81356001600160a01b03811681146101de57600080fd5b939250505056fea2646970667358221220913029acecaa70fea34e3e4a4c174de7a35c26a7a78e696d4a6c61dc5654b34764736f6c634300080b0033";

export class IncentivePoolView__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides & { from?: string | Promise<string> }): Promise<IncentivePoolView> {
    return super.deploy(overrides || {}) as Promise<IncentivePoolView>;
  }
  getDeployTransaction(overrides?: Overrides & { from?: string | Promise<string> }): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): IncentivePoolView {
    return super.attach(address) as IncentivePoolView;
  }
  connect(signer: Signer): IncentivePoolView__factory {
    return super.connect(signer) as IncentivePoolView__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): IncentivePoolViewInterface {
    return new utils.Interface(_abi) as IncentivePoolViewInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IncentivePoolView {
    return new Contract(address, _abi, signerOrProvider) as IncentivePoolView;
  }
}
